require("dotenv").config();

const express = require("express");
const morgan = require("morgan");
const app = express();

const Person = require("./models/person.model");

// Plugins
// * Use frontend generated by Vite
app.use(express.static("frontend/dist"));
app.use(express.json());
morgan.token("body", (request) => JSON.stringify(request.body));
app.use(morgan(":method :url :status :body - :response-time ms"));

// Config

const PORT = process.env.PORT || 3001;

// Routes

{
  app.get("/api/persons", (_request, response) => {
    Person.find({}).then((people) => {
      response.json(people);
    });
  });

  app.get("/info", (_request, response, next) => {
    Person.find({})
      .then((people) => {
        response.send(
          `
        <!DOCTYPE html>
        <html>
          <body>
          <p>Phonebook has info for ${people.length} people</p>
          <p>${new Date().toISOString()}</p>
          </body>
          </html>
          `,
        );
      })
      .catch((error) => next(error));
  });

  app.get("/api/persons/:id", (request, response, next) => {
    Person.findById(request.params.id)
      .then((r) => {
        response.json(r);
      })
      .catch((error) => next(error));
    // const found = Person.find((each) => each.id == request.params.id);

    // if (!found) {
    //   return response.status(404).end();
    // }

    // response.json(found);
  });

  app.delete("/api/persons/:id", (request, response, next) => {
    // const foundIndex = phonenumbers.findIndex(
    //   (each) => each.id == request.params.id,
    // );

    // if (foundIndex === -1) {
    //   return response.status(404).end();
    // }

    // const deletedObject = phonenumbers[foundIndex];

    // phonenumbers = phonenumbers.filter((_, i) => i !== foundIndex);

    Person.findByIdAndDelete(request.params.id)
      .then((r) => response.json(r))
      .catch((error) => next(error));
  });

  app.post("/api/persons", (request, response, next) => {
    const body = request.body;
    // const object = {
    //   id: Math.round(Math.random() * 1000000),
    //   ...body,
    // };

    if (!body) {
      return response.status(400).json({ error: "body doesn't exist" });
    }

    if (!body.name) {
      return response.status(400).json({ error: "name must be defined" });
    }

    if (!body.number) {
      return response.status(400).json({ error: "number must be defined" });
    }

    // if (phonenumbers.some((each) => each.name === object.name)) {
    //   return response
    //     .status(400)
    //     .json({ error: "name is already registered!" });
    // }

    // phonenumbers = [...phonenumbers, object];

    new Person({
      name: body.name,
      number: body.number,
    })
      .save()
      .then((r) => {
        response.json(r);
      })
      .catch((error) => next(error));
  });

  app.put("/api/persons/:id", (request, response, next) => {
    const body = request.body;

    if (!body) {
      return response.status(400).json({ error: "body doesn't exist" });
    }

    if (!body.name) {
      return response.status(400).json({ error: "name must be defined" });
    }

    if (!body.number) {
      return response.status(400).json({ error: "number must be defined" });
    }

    Person.findOneAndUpdate(
      {
        _id: request.params.id,
      },
      {
        name: body.name,
        number: body.number,
      },
      { new: true, runValidators: true, context: "query" },
    )
      .then((r) => response.json(r))
      .catch((error) => next(error));
  });
}

// Middleware
{
  const errorHandler = (error, request, response, next) => {
    console.error(error.message);

    if (error.name === "CastError") {
      return response.status(400).send({ error: "malformatted id" });
    } else if (error.name === "ValidationError") {
      return response.status(400).json({ error: error.message });
    }

    next(error);
  };

  app.use(errorHandler);
}

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
